/*============================================= FUNCIONES DE SELECCION =========================================*/

CREATE TYPE T_PAIS_ROW AS OBJECT
(
  ID_PAIS INTEGER, 
  NOMBRE VARCHAR2(100), 
  NACIONALIDAD VARCHAR2(100)
);

CREATE OR REPLACE TYPE T_PAIS_TABLE AS TABLE OF T_PAIS_ROW;

CREATE OR REPLACE FUNCTION FN_PAIS_SELECT(pNOMBRE PAIS.NOMBRE%TYPE) RETURN  T_PAIS_TABLE PIPELINED AS
  CURSOR cPAIS IS
  SELECT ID_PAIS, NOMBRE, NACIONALIDAD 
  FROM PAIS 
  WHERE NOMBRE LIKE pNOMBRE;  
BEGIN
  FOR reg in cPAIS LOOP
    PIPE ROW(T_PAIS_ROW(reg.ID_PAIS, reg.NOMBRE, reg.NACIONALIDAD));
  END LOOP;
  RETURN;
END;

---------------------------------------------------------
CREATE TYPE T_CIUDAD_ROW AS OBJECT
(
  ID_CIUDAD INTEGER, 
  ID_PAIS INTEGER,
  NOMBRE VARCHAR2(100)
);

CREATE OR REPLACE TYPE T_CIUDAD_TABLE AS TABLE OF T_CIUDAD_ROW;

CREATE OR REPLACE FUNCTION FN_CIUDAD_SELECT(pNOMBRE CIUDAD.NOMBRE%TYPE) RETURN  T_CIUDAD_TABLE PIPELINED AS
  CURSOR cCIUDAD IS
  SELECT ID_CIUDAD,ID_PAIS,NOMBRE
  FROM CIUDAD
  WHERE NOMBRE LIKE pNOMBRE;  
BEGIN
  FOR reg in cCIUDAD LOOP
    PIPE ROW(T_CIUDAD_ROW(reg.ID_CIUDAD,reg.ID_PAIS,reg.NOMBRE));
  END LOOP;
  RETURN;
END;

---------------------------------------------------------
CREATE TYPE T_COMPETENCIA_ROW AS OBJECT
(
  ID_COMPETENCIA INTEGER,
  NOMBRE VARCHAR2(60),
  FECHA_INICIO DATE,
  FECHA_FIN DATE,
  ESTADO_ACTUAL INTEGER
);

CREATE OR REPLACE TYPE T_COMPETENCIA_TABLE AS TABLE OF T_COMPETENCIA_ROW;

CREATE OR REPLACE FUNCTION FN_COMPETENCIA_SELECT(pNOMBRE COMPETENCIA.NOMBRE%TYPE) RETURN  T_COMPETENCIA_TABLE PIPELINED AS
  CURSOR cCOMPETENCIA IS
  SELECT *
  FROM COMPETENCIA
  WHERE NOMBRE LIKE pNOMBRE;  
BEGIN
  FOR reg in cCOMPETENCIA LOOP
    PIPE ROW(T_COMPETENCIA_ROW(reg.ID_COMPETENCIA,reg.NOMBRE,reg.FECHA_INICIO,reg.FECHA_FIN,reg.ESTADO_ACTUAL));
  END LOOP;
  RETURN;
END;

---------------------------------------------------------
CREATE TYPE T_DESEMPENIO_DMD_ROW AS OBJECT
(
  ID_JUGADOR INTEGER,
  ID_RESULTADO INTEGER,
  VELOCIDAD INTEGER,
  CAPACIDAD_PASE INTEGER,
  CAPACIDAD_MARCA INTEGER,
  TIRO_GOL INTEGER
);

CREATE OR REPLACE TYPE T_DESEMPENIO_DMD_TABLE AS TABLE OF T_DESEMPENIO_DMD_ROW;

CREATE OR REPLACE FUNCTION FN_DESEMPENIO_DMD_SELECT(pID_JUGADOR DESEMPENIO_DMD.ID_JUGADOR%TYPE) RETURN  T_DESEMPENIO_DMD_TABLE PIPELINED AS
  CURSOR cDESEMPENIO_DMD IS
  SELECT *
  FROM DESEMPENIO_DMD
  WHERE ID_JUGADOR LIKE pID_JUGADOR;  
BEGIN
  FOR reg in cDESEMPENIO_DMD LOOP
    PIPE ROW(T_DESEMPENIO_DMD_ROW(reg.ID_JUGADOR,reg.ID_RESULTADO,reg.VELOCIDAD,reg.CAPACIDAD_PASE,reg.CAPACIDAD_MARCA,reg.TIRO_GOL));
  END LOOP;
  RETURN;
END;

---------------------------------------------------------
CREATE TYPE T_DESEMPENIO_PORTERO_ROW AS OBJECT
(
  ID_JUGADOR INTEGER,
  ID_RESULTADO INTEGER,
  CAPACIDAD_ATAJAR INTEGER,
  LUCHA1_1 INTEGER,
  ANTICIPACION INTEGER,
  REFLEJOS INTEGER
);

CREATE OR REPLACE TYPE T_DESEMPENIO_PORTERO_TABLE AS TABLE OF T_DESEMPENIO_PORTERO_ROW;

CREATE OR REPLACE FUNCTION FN_DESEMPENIO_PORTERO_SELECT(pID_JUGADOR DESEMPENIO_PORTERO.ID_JUGADOR%TYPE) RETURN  T_DESEMPENIO_PORTERO_TABLE PIPELINED AS
  CURSOR cDESEMPENIO_PORTERO IS
  SELECT *
  FROM DESEMPENIO_PORTERO
  WHERE ID_JUGADOR LIKE pID_JUGADOR;  
BEGIN
  FOR reg in cDESEMPENIO_PORTERO LOOP
    PIPE ROW(T_DESEMPENIO_PORTERO_ROW(reg.ID_JUGADOR,reg.ID_RESULTADO,reg.CAPACIDAD_ATAJAR,reg.LUCHA1_1,reg.ANTICIPACION,reg.REFLEJOS));
  END LOOP;
  RETURN;
END;

---------------------------------------------------------
CREATE TYPE T_ENTRENADOR_ROW AS OBJECT
(
  ID_ENTRENADOR INTEGER,
  ID_PAIS INTEGER,
  NOMBRE VARCHAR2(100),
  EDAD INTEGER,
  CEDULA_IDENTIDAD INTEGER,
  BIOGRAFIA CLOB,
  FOTO BLOB
);

CREATE OR REPLACE TYPE T_ENTRENADOR_TABLE AS TABLE OF T_ENTRENADOR_ROW;

CREATE OR REPLACE FUNCTION FN_ENTRENADOR_SELECT(pNOMBRE ENTRENADOR.NOMBRE%TYPE) RETURN  T_ENTRENADOR_TABLE PIPELINED AS
  CURSOR cENTRENADOR IS
  SELECT *
  FROM ENTRENADOR
  WHERE NOMBRE LIKE pNOMBRE;  
BEGIN
  FOR reg in cENTRENADOR LOOP
    PIPE ROW(T_ENTRENADOR_ROW(reg.ID_ENTRENADOR,reg.ID_PAIS,reg.NOMBRE,reg.EDAD,reg.CEDULA_IDENTIDAD,reg.BIOGRAFIA,reg.FOTO));
  END LOOP;
  RETURN;
END;

---------------------------------------------------------
CREATE TYPE T_EQUIPO_ROW AS OBJECT
(
  ID_EQUIPO INTEGER,
  ID_CIUDAD INTEGER,
  ID_ENTRENADOR INTEGER,
  NOMBRE VARCHAR2(100),
  FECHA_FUNDACION DATE,
  NUMERO_COPASGANADAS INTEGER,
  LOGOTIPO BLOB,
  TIPO VARCHAR2(20)
);

CREATE OR REPLACE TYPE T_EQUIPO_TABLE AS TABLE OF T_EQUIPO_ROW;

CREATE OR REPLACE FUNCTION FN_EQUIPO_SELECT(pNOMBRE EQUIPO.NOMBRE%TYPE) RETURN  T_EQUIPO_TABLE PIPELINED AS
  CURSOR cEQUIPO IS
  SELECT *
  FROM EQUIPO
  WHERE NOMBRE LIKE pNOMBRE;  
BEGIN
  FOR reg in cEQUIPO LOOP
    PIPE ROW(T_EQUIPO_ROW(reg.ID_EQUIPO,reg.ID_CIUDAD,reg.ID_ENTRENADOR,reg.NOMBRE,reg.FECHA_FUNDACION,reg.NUMERO_COPASGANADAS,reg.LOGOTIPO,reg.TIPO));
  END LOOP;
  RETURN;
END;

---------------------------------------------------------
CREATE TYPE T_ESTADIO_ROW AS OBJECT
(
  ID_ESTADIO INTEGER,
  ID_CIUDAD INTEGER,
  NOMBRE VARCHAR2(100),
  CAPACIDAD INTEGER,
  FECHA_INAUGURACION DATE,
  HISTORIA CLOB
);

CREATE OR REPLACE TYPE T_ESTADIO_TABLE AS TABLE OF T_ESTADIO_ROW;

CREATE OR REPLACE FUNCTION FN_ESTADIO_SELECT(pNOMBRE ESTADIO.NOMBRE%TYPE) RETURN  T_ESTADIO_TABLE PIPELINED AS
  CURSOR cESTADIO IS
  SELECT *
  FROM ESTADIO
  WHERE NOMBRE LIKE pNOMBRE;  
BEGIN
  FOR reg in cESTADIO LOOP
    PIPE ROW(T_ESTADIO_ROW(reg.ID_ESTADIO,reg.ID_CIUDAD,reg.NOMBRE,reg.CAPACIDAD,reg.FECHA_INAUGURACION,reg.HISTORIA));
  END LOOP;
  RETURN;
END;

---------------------------------------------------------
CREATE TYPE T_JUGADOR_ROW AS OBJECT
(
  ID_JUGADOR INTEGER,
  ID_PAIS INTEGER,
  CEDULA_IDENTIDAD INTEGER,
  NOMBRE VARCHAR2(100),
  EDAD INTEGER,
  PERO NUMBER,
  POSICION VARCHAR2(25),
  BIOGRAFIA CLOB,
  FOTO BLOB
);

CREATE OR REPLACE TYPE T_JUGADOR_TABLE AS TABLE OF T_JUGADOR_ROW;

CREATE OR REPLACE FUNCTION FN_JUGADOR_SELECT(pNOMBRE JUGADOR.NOMBRE%TYPE) RETURN  T_JUGADOR_TABLE PIPELINED AS
  CURSOR cJUGADOR IS
  SELECT *
  FROM JUGADOR
  WHERE NOMBRE LIKE pNOMBRE;  
BEGIN
  FOR reg in cJUGADOR LOOP
    PIPE ROW(T_JUGADOR_ROW(reg.ID_JUGADOR,reg.ID_PAIS,reg.CEDULA_IDENTIDAD,reg.NOMBRE,reg.EDAD,reg.PESO,reg.POSICION,reg.BIOGRAFIA,reg.FOTO));
  END LOOP;
  RETURN;
END;

---------------------------------------------------------
CREATE TYPE T_PARTIDO_ROW AS OBJECT
(
  ID_PARTIDO INTEGER,
  ID_COMPETENCIA INTEGER,
  ID_ESTADIO INTEGER,
  ID_EQUIPO_LOCAL INTEGER,
  ID_EQUIPO_VISITA INTEGER,
  FECHA_PARTIDO DATE,
  HORA_INICIO NUMBER,
  ESTADO INTEGER
);

CREATE OR REPLACE TYPE T_PARTIDO_TABLE AS TABLE OF T_PARTIDO_ROW;

CREATE OR REPLACE FUNCTION FN_PARTIDO_SELECT(pID_EQUIPO_LOCAL PARTIDO.ID_EQUIPO_LOCAL%TYPE) RETURN  T_PARTIDO_TABLE PIPELINED AS
  CURSOR cPARTIDO IS
  SELECT *
  FROM PARTIDO
  WHERE ID_EQUIPO_LOCAL LIKE pID_EQUIPO_LOCAL;  
BEGIN
  FOR reg in cPARTIDO LOOP
    PIPE ROW(T_PARTIDO_ROW(reg.ID_PARTIDO,reg.ID_COMPETENCIA,reg.ID_ESTADIO,reg.ID_EQUIPO_LOCAL,reg.ID_EQUIPO_VISITA,reg.FECHA_PARTIDO,reg.HORA_INICIO,reg.ESTADO));
  END LOOP;
  RETURN;
END;

---------------------------------------------------------
CREATE TYPE T_RESULTADO_ROW AS OBJECT
(
  ID_RESULTADO INTEGER, 
  ID_PARTIDO INTEGER, 
  PRIMERT_GOLES_EQUIPO1 INTEGER, 
  PRIMERT_GOLES_EQUIPO2 INTEGER, 
  SEGUNDOT_GOLES_EQUIPO1 INTEGER, 
  SEGUNDOT_GOLES_EQUIPO2 INTEGER, 
  TIEMPOEXTRA_GOLES_EQUIPO1 INTEGER, 
  TIEMPOEXTRA_GOLES_EQUIPO2 INTEGER, 
  PENALES_GOLES_EQUIPO1 INTEGER, 
  PENALES_GOLES_EQUIPO2 INTEGER, 
  TARJETAS_A_EQUIPO1 INTEGER, 
  TARJETAS_A_EQUIPO2 INTEGER, 
  TARJETAS_R_EQUIPO1 INTEGER, 
  TARJETAS_R_EQUIPO2 INTEGER,
  
  --- AQUI SE AGREGAN LOS TRES CAMPOS CALCULADOS
  RESULTADO_FINAL_EQUIPO1 INTEGER,
  RESULTADO_FINAL_EQUIPO2 INTEGER,
  EQUIPO_GANADOR VARCHAR2(100)
);

CREATE OR REPLACE TYPE T_RESULTADO_TABLE AS TABLE OF T_RESULTADO_ROW;

CREATE OR REPLACE FUNCTION FN_RESULTADO_SELECT(pID_PARTIDO RESULTADO.ID_PARTIDO%TYPE) RETURN  T_RESULTADO_TABLE PIPELINED AS
  CURSOR cRESULTADO IS
  SELECT *
  FROM RESULTADO
  WHERE ID_PARTIDO LIKE pID_PARTIDO; 
  nRESULTADO_EQUIPO1 INTEGER;
  nRESULTADO_EQUIPO2 INTEGER;
  nEQUIPO_GANADOR VARCHAR2(100);
BEGIN
  FOR reg in cRESULTADO LOOP
    nRESULTADO_EQUIPO1 := (NVL(reg.PRIMERT_GOLES_EQUIPO1,0)+NVL(reg.SEGUNDOT_GOLES_EQUIPO1,0)+NVL(reg.TIEMPOEXTRA_GOLES_EQUIPO1,0)+
                          NVL(reg.PENALES_GOLES_EQUIPO1,0));
    nRESULTADO_EQUIPO2 := (NVL(reg.PRIMERT_GOLES_EQUIPO2,0)+NVL(reg.SEGUNDOT_GOLES_EQUIPO2,0)+NVL(reg.TIEMPOEXTRA_GOLES_EQUIPO2,0)+
                          NVL(reg.PENALES_GOLES_EQUIPO2,0)); 
    IF nRESULTADO_EQUIPO1 > nRESULTADO_EQUIPO2 THEN
      SELECT FN_GET_EQUIPO_GANADOR(1,pID_PARTIDO)INTO nEQUIPO_GANADOR FROM DUAL;
    ELSE IF nRESULTADO_EQUIPO2 > nRESULTADO_EQUIPO1 THEN
      SELECT FN_GET_EQUIPO_GANADOR(2,pID_PARTIDO) INTO nEQUIPO_GANADOR FROM DUAL;
    ELSE
      nEQUIPO_GANADOR := 'EMPATE';
    END IF;
    END IF;
    PIPE ROW(T_RESULTADO_ROW( reg.ID_RESULTADO, reg.ID_PARTIDO, reg.PRIMERT_GOLES_EQUIPO1, reg.PRIMERT_GOLES_EQUIPO2, reg.SEGUNDOT_GOLES_EQUIPO1,
                              reg.SEGUNDOT_GOLES_EQUIPO2, reg.TIEMPOEXTRA_GOLES_EQUIPO1, reg.TIEMPOEXTRA_GOLES_EQUIPO2, reg.PENALES_GOLES_EQUIPO1,
                              reg.PENALES_GOLES_EQUIPO2, reg.TARJETAS_A_EQUIPO1, reg.TARJETAS_A_EQUIPO2, reg.TARJETAS_R_EQUIPO1, reg.TARJETAS_R_EQUIPO2,
                              nRESULTADO_EQUIPO1, nRESULTADO_EQUIPO2, nEQUIPO_GANADOR));
  END LOOP;
  RETURN;
END;

--- FUNCION AUXILIAR PARA CALCULAR EL EQUIPO, QUE SEGUN EL RESULTADO FINAL DEL PARTIDO DETERMINE SI ES GANADOR
CREATE OR REPLACE FUNCTION FN_GET_EQUIPO_GANADOR(pEQUIPO INTEGER, pID_PARTIDO INTEGER) RETURN VARCHAR2 AS
vNOMBRE VARCHAR2(100);
BEGIN
  IF pEQUIPO = 1 THEN
    SELECT NOMBRE INTO vNOMBRE FROM EQUIPO, 
    (SELECT PARTIDO.ID_EQUIPO_LOCAL, PARTIDO.ID_EQUIPO_VISITA FROM PARTIDO, RESULTADO
    WHERE PARTIDO.ID_PARTIDO = RESULTADO.ID_PARTIDO AND PARTIDO.ID_PARTIDO = pID_PARTIDO)S
    WHERE S.ID_EQUIPO_LOCAL = EQUIPO.ID_EQUIPO;
  ELSE IF pEQUIPO = 2 THEN
    SELECT NOMBRE INTO vNOMBRE FROM EQUIPO, 
    (SELECT PARTIDO.ID_EQUIPO_LOCAL, PARTIDO.ID_EQUIPO_VISITA FROM PARTIDO, RESULTADO
    WHERE PARTIDO.ID_PARTIDO = RESULTADO.ID_PARTIDO AND PARTIDO.ID_PARTIDO = pID_PARTIDO)S
    WHERE S.ID_EQUIPO_VISITA = EQUIPO.ID_EQUIPO;
  END IF;
  END IF;
  RETURN vNOMBRE;
END;
--- PRUEBA DE LA FUNCION SELECT DE RESULTADO CON LA INFO DE LOS CAMPOS CALCULADOS
SELECT * FROM TABLE(FN_RESULTADO_SELECT(4));


