/*======================================================= SECUENCIAS =================================================*/

CREATE SEQUENCE  "FIFA_TB1"."SEQ_CIUDAD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;

CREATE SEQUENCE  "FIFA_TB1"."SEQ_COMPETENCIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE SEQUENCE  "FIFA_TB1"."SEQ_ENTRENADOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE SEQUENCE  "FIFA_TB1"."SEQ_EQUIPO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE SEQUENCE  "FIFA_TB1"."SEQ_ESTADIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE SEQUENCE  "FIFA_TB1"."SEQ_JUGADOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE SEQUENCE  "FIFA_TB1"."SEQ_PAIS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;

CREATE SEQUENCE  "FIFA_TB1"."SEQ_PARTIDO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE SEQUENCE  "FIFA_TB1"."SEQ_RESULTADO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

/*==================================================== DISPARADORES =====================================================*/

CREATE OR REPLACE TRIGGER TR_ID_CIUDAD 
BEFORE INSERT ON CIUDAD 
FOR EACH ROW
BEGIN
  SELECT SEQ_CIUDAD.NEXTVAL INTO :NEW.ID_CIUDAD FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TR_ID_COMPETENCIA 
BEFORE INSERT ON COMPETENCIA 
FOR EACH ROW
BEGIN
  SELECT SEQ_COMPETENCIA.NEXTVAL INTO :NEW.ID_COMPETENCIA FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TR_ID_ENTRENADOR 
BEFORE INSERT ON ENTRENADOR 
FOR EACH ROW
BEGIN
  SELECT SEQ_ENTRENADOR.NEXTVAL INTO :NEW.ID_ENTRENADOR FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TR_ID_EQUIPO 
BEFORE INSERT ON EQUIPO 
FOR EACH ROW
BEGIN
  SELECT SEQ_EQUIPO.NEXTVAL INTO :NEW.ID_EQUIPO FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TR_ID_ESTADIO 
BEFORE INSERT ON ESTADIO 
FOR EACH ROW
BEGIN
  SELECT SEQ_ESTADIO.NEXTVAL INTO :NEW.ID_ESTADIO FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TR_ID_JUGADOR 
BEFORE INSERT ON JUGADOR 
FOR EACH ROW
BEGIN
  SELECT SEQ_JUGADOR.NEXTVAL INTO :NEW.ID_JUGADOR FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TR_ID_PAIS 
BEFORE INSERT ON PAIS 
FOR EACH ROW
BEGIN
  SELECT SEQ_PAIS.NEXTVAL INTO :NEW.ID_PAIS FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TR_ID_PARTIDO 
BEFORE INSERT ON PARTIDO 
FOR EACH ROW
BEGIN
  SELECT SEQ_PARTIDO.NEXTVAL INTO :NEW.ID_PARTIDO FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TR_ID_RESULTADO 
BEFORE INSERT ON RESULTADO 
FOR EACH ROW
BEGIN
  SELECT SEQ_RESULTADO.NEXTVAL INTO :NEW.ID_RESULTADO FROM DUAL;
END;