-- Generado por Oracle SQL Developer Data Modeler 4.0.1.836
--   en:        2014-05-26 03:36:17 CST
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLE CIUDAD
  (
    ID_CIUDAD INTEGER NOT NULL ,
    ID_PAIS   INTEGER NOT NULL ,
    NOMBRE    VARCHAR2 (100)
  ) ;
ALTER TABLE CIUDAD ADD CONSTRAINT CIUDAD_PK PRIMARY KEY ( ID_CIUDAD ) ;

CREATE TABLE COMPETENCIA
  (
    ID_COMPETENCIA INTEGER NOT NULL ,
    NOMBRE         VARCHAR2 (60) ,
    FECHA_INICIO   DATE ,
    FECHA_FIN      DATE ,
    ESTADO_ACTUAL  INTEGER
  ) ;
ALTER TABLE COMPETENCIA ADD CONSTRAINT COMPETENCIA_PK PRIMARY KEY ( ID_COMPETENCIA ) ;

CREATE TABLE COMPETENCIA_ESTADIO
  (
    ID_COMPETENCIA INTEGER NOT NULL ,
    ID_ESTADIO     INTEGER NOT NULL
  ) ;
ALTER TABLE COMPETENCIA_ESTADIO ADD CONSTRAINT COMPETENCIA_ESTADIO_PK PRIMARY KEY ( ID_COMPETENCIA, ID_ESTADIO ) ;

CREATE TABLE DESEMPENIO_DMD
  (
    ID_JUGADOR      INTEGER NOT NULL ,
    ID_RESULTADO    INTEGER NOT NULL ,
    VELOCIDAD       INTEGER ,
    CAPACIDAD_PASE  INTEGER ,
    CAPACIDAD_MARCA INTEGER ,
    TIRO_GOL        INTEGER
  ) ;
ALTER TABLE DESEMPENIO_DMD ADD CONSTRAINT DESEMPENIO_DMD_PK PRIMARY KEY ( ID_JUGADOR, ID_RESULTADO ) ;

CREATE TABLE DESEMPENIO_PORTERO
  (
    ID_JUGADOR       INTEGER NOT NULL ,
    ID_RESULTADO     INTEGER NOT NULL ,
    CAPACIDAD_ATAJAR INTEGER ,
    LUCHA1_1         INTEGER ,
    ANTICIPACION     INTEGER ,
    REFLEJOS         INTEGER
  ) ;
ALTER TABLE DESEMPENIO_PORTERO ADD CONSTRAINT DESEMPENIO_PORTERO_PK PRIMARY KEY ( ID_JUGADOR, ID_RESULTADO ) ;

CREATE TABLE ENTRENADOR
  (
    ID_ENTRENADOR    INTEGER NOT NULL ,
    ID_PAIS          INTEGER NOT NULL ,
    NOMBRE           VARCHAR2 (100) ,
    EDAD             INTEGER ,
    CEDULA_IDENTIDAD INTEGER ,
    BIOGRAFIA CLOB ,
    FOTO BLOB
  ) ;
ALTER TABLE ENTRENADOR ADD CONSTRAINT ENTRENADOR_PK PRIMARY KEY ( ID_ENTRENADOR ) ;

CREATE TABLE EQUIPO
  (
    ID_EQUIPO           INTEGER NOT NULL ,
    ID_CIUDAD           INTEGER NOT NULL ,
    ID_ENTRENADOR       INTEGER NOT NULL ,
    NOMBRE              VARCHAR2 (100) ,
    FECHA_FUNDACION     DATE ,
    NUMERO_COPASGANADAS INTEGER ,
    LOGOTIPO BLOB
  ) ;
ALTER TABLE EQUIPO ADD CONSTRAINT EQUIPO_PK PRIMARY KEY ( ID_EQUIPO ) ;

CREATE TABLE EQUIPO_COMPETENCIA
  (
    ID_EQUIPO      INTEGER NOT NULL ,
    ID_COMPETENCIA INTEGER NOT NULL ,
    PUNTOS         INTEGER ,
    POSICION       INTEGER
  ) ;
ALTER TABLE EQUIPO_COMPETENCIA ADD CONSTRAINT EQUIPO_COMPETENCIA_PK PRIMARY KEY ( ID_EQUIPO, ID_COMPETENCIA ) ;

CREATE TABLE EQUIPO_JUGADOR
  (
    ID_EQUIPO       INTEGER NOT NULL ,
    ID_JUGADOR      INTEGER NOT NULL ,
    NUMERO_CAMISOLA INTEGER
  ) ;
ALTER TABLE EQUIPO_JUGADOR ADD CONSTRAINT EQUIPO_JUGADOR_PK PRIMARY KEY ( ID_JUGADOR, ID_EQUIPO ) ;

CREATE TABLE ESTADIO
  (
    ID_ESTADIO         INTEGER NOT NULL ,
    ID_CIUDAD          INTEGER NOT NULL ,
    NOMBRE             VARCHAR2 (100) ,
    CAPACIDAD          INTEGER ,
    FECHA_INAUGURACION DATE ,
    HISTORIA CLOB
  ) ;
ALTER TABLE ESTADIO ADD CONSTRAINT ESTADIO_PK PRIMARY KEY ( ID_ESTADIO ) ;

CREATE TABLE JUGADOR
  (
    ID_JUGADOR       INTEGER NOT NULL ,
    ID_PAIS          INTEGER NOT NULL ,
    CEDULA_IDENTIDAD INTEGER ,
    NOMBRE           VARCHAR2 (100) ,
    EDAD             INTEGER ,
    PESO             NUMBER ,
    POSICION         VARCHAR2 (25) ,
    BIOGRAFIA CLOB ,
    FOTO BLOB
  ) ;
ALTER TABLE JUGADOR ADD CONSTRAINT JUGADOR_PK PRIMARY KEY ( ID_JUGADOR ) ;

CREATE TABLE PAIS
  (
    ID_PAIS      INTEGER NOT NULL ,
    NOMBRE       VARCHAR2 (100) ,
    NACIONALIDAD VARCHAR2 (100)
  ) ;
ALTER TABLE PAIS ADD CONSTRAINT PAIS_PK PRIMARY KEY ( ID_PAIS ) ;

CREATE TABLE PARTIDO
  (
    ID_PARTIDO       INTEGER NOT NULL ,
    ID_COMPETENCIA   INTEGER NOT NULL ,
    ID_ESTADIO       INTEGER NOT NULL ,
    ID_EQUIPO_LOCAL  INTEGER NOT NULL ,
    ID_EQUIPO_VISITA INTEGER NOT NULL ,
    FECHA_PARTIDO    DATE ,
    HORA_INICIO      NUMBER ,
    ESTADO           INTEGER
  ) ;
ALTER TABLE PARTIDO ADD CONSTRAINT PARTIDO_PK PRIMARY KEY ( ID_PARTIDO ) ;

CREATE TABLE RESULTADO
  (
    ID_RESULTADO              INTEGER NOT NULL ,
    ID_PARTIDO                INTEGER NOT NULL ,
    PRIMERT_GOLES_EQUIPO1     INTEGER ,
    PRIMERT_GOLES_EQUIPO2     INTEGER ,
    SEGUNDOT_GOLES_EQUIPO1    INTEGER ,
    SEGUNDOT_GOLES_EQUIPO2    INTEGER ,
    TIEMPOEXTRA_GOLES_EQUIPO1 INTEGER ,
    TIEMPOEXTRA_GOLES_EQUIPO2 INTEGER ,
    PENALES_GOLES_EQUIPOS1    INTEGER ,
    PENALES_GOLES_EQUIPO2     INTEGER ,
    TARJETAS_A_EQUIPO1        INTEGER ,
    TARJETAS_A_EQUIPO2        INTEGER ,
    TARJETAS_R_EQUIPO1        INTEGER ,
    TARJETAS_R_EQUIPO2        INTEGER
  ) ;
ALTER TABLE RESULTADO ADD CONSTRAINT RESULTADO_PK PRIMARY KEY ( ID_RESULTADO ) ;

ALTER TABLE CIUDAD ADD CONSTRAINT CIUDAD_SE_ENCUENTRA_PAIS FOREIGN KEY ( ID_PAIS ) REFERENCES PAIS ( ID_PAIS ) ;

ALTER TABLE COMPETENCIA_ESTADIO ADD CONSTRAINT COMPETENCIA_JUEGA_ESTADIOS FOREIGN KEY ( ID_COMPETENCIA ) REFERENCES COMPETENCIA ( ID_COMPETENCIA ) ;

ALTER TABLE PARTIDO ADD CONSTRAINT COMPETENCIA_SE_JUEGAN FOREIGN KEY ( ID_COMPETENCIA ) REFERENCES COMPETENCIA ( ID_COMPETENCIA ) ;

ALTER TABLE EQUIPO_COMPETENCIA ADD CONSTRAINT COMPETENCIA_TIENE FOREIGN KEY ( ID_COMPETENCIA ) REFERENCES COMPETENCIA ( ID_COMPETENCIA ) ;

ALTER TABLE DESEMPENIO_DMD ADD CONSTRAINT DESEMPENIO_DMD_EVALUA FOREIGN KEY ( ID_RESULTADO ) REFERENCES RESULTADO ( ID_RESULTADO ) ;

ALTER TABLE DESEMPENIO_DMD ADD CONSTRAINT DESEMPENIO_DMD_JUGADOR FOREIGN KEY ( ID_JUGADOR ) REFERENCES JUGADOR ( ID_JUGADOR ) ;

ALTER TABLE DESEMPENIO_PORTERO ADD CONSTRAINT DESEMPENIO_PORTERO_EVALUA FOREIGN KEY ( ID_RESULTADO ) REFERENCES RESULTADO ( ID_RESULTADO ) ;

ALTER TABLE DESEMPENIO_PORTERO ADD CONSTRAINT DESEMPENIO_PORTERO_JUGADOR FOREIGN KEY ( ID_JUGADOR ) REFERENCES JUGADOR ( ID_JUGADOR ) ;

ALTER TABLE ENTRENADOR ADD CONSTRAINT ENTRENADOR_NACIO_PAIS FOREIGN KEY ( ID_PAIS ) REFERENCES PAIS ( ID_PAIS ) ;

ALTER TABLE EQUIPO ADD CONSTRAINT EQUIPO_ES_DE_CIUDAD FOREIGN KEY ( ID_CIUDAD ) REFERENCES CIUDAD ( ID_CIUDAD ) ;

ALTER TABLE EQUIPO_COMPETENCIA ADD CONSTRAINT EQUIPO_JUEGA_EN_COMPETENCIA FOREIGN KEY ( ID_EQUIPO ) REFERENCES EQUIPO ( ID_EQUIPO ) ;

ALTER TABLE EQUIPO_JUGADOR ADD CONSTRAINT EQUIPO_TIENE FOREIGN KEY ( ID_EQUIPO ) REFERENCES EQUIPO ( ID_EQUIPO ) ;

ALTER TABLE EQUIPO ADD CONSTRAINT EQUIPO_TIENE_ENTRENADOR FOREIGN KEY ( ID_ENTRENADOR ) REFERENCES ENTRENADOR ( ID_ENTRENADOR ) ;

ALTER TABLE COMPETENCIA_ESTADIO ADD CONSTRAINT ESTADIO_COMPITEN_COMPETENCIAS FOREIGN KEY ( ID_ESTADIO ) REFERENCES ESTADIO ( ID_ESTADIO ) ;

ALTER TABLE ESTADIO ADD CONSTRAINT ESTADIO_PERTENECE_CIUDAD FOREIGN KEY ( ID_CIUDAD ) REFERENCES CIUDAD ( ID_CIUDAD ) ;

ALTER TABLE JUGADOR ADD CONSTRAINT JUGADOR_NACIO_PAIS FOREIGN KEY ( ID_PAIS ) REFERENCES PAIS ( ID_PAIS ) ;

ALTER TABLE EQUIPO_JUGADOR ADD CONSTRAINT JUGADOR_PERTENECE FOREIGN KEY ( ID_JUGADOR ) REFERENCES JUGADOR ( ID_JUGADOR ) ;

ALTER TABLE PARTIDO ADD CONSTRAINT PARTIDO_LOCAL_EQUIPO FOREIGN KEY ( ID_EQUIPO_LOCAL ) REFERENCES EQUIPO ( ID_EQUIPO ) ;

ALTER TABLE PARTIDO ADD CONSTRAINT PARTIDO_SE_JUEGA_ESTADIO FOREIGN KEY ( ID_ESTADIO ) REFERENCES ESTADIO ( ID_ESTADIO ) ;

ALTER TABLE PARTIDO ADD CONSTRAINT PARTIDO_VISITA_EQUIPO FOREIGN KEY ( ID_EQUIPO_VISITA ) REFERENCES EQUIPO ( ID_EQUIPO ) ;

ALTER TABLE RESULTADO ADD CONSTRAINT RESULTADO_TIENE_PARTIDO FOREIGN KEY ( ID_PARTIDO ) REFERENCES PARTIDO ( ID_PARTIDO ) ;


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             35
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
