//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUDAD
    {
        public CIUDAD()
        {
            this.EQUIPO = new HashSet<EQUIPO>();
            this.ESTADIO = new HashSet<ESTADIO>();
        }
    
        public decimal ID_CIUDAD { get; set; }
        public decimal ID_PAIS { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual PAIS PAIS { get; set; }
        public virtual ICollection<EQUIPO> EQUIPO { get; set; }
        public virtual ICollection<ESTADIO> ESTADIO { get; set; }
    }
}
