//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CIUDAD> CIUDAD { get; set; }
        public DbSet<COMPETENCIA> COMPETENCIA { get; set; }
        public DbSet<DESEMPENIO_DMD> DESEMPENIO_DMD { get; set; }
        public DbSet<DESEMPENIO_PORTERO> DESEMPENIO_PORTERO { get; set; }
        public DbSet<ENTRENADOR> ENTRENADOR { get; set; }
        public DbSet<EQUIPO> EQUIPO { get; set; }
        public DbSet<EQUIPO_COMPETENCIA> EQUIPO_COMPETENCIA { get; set; }
        public DbSet<EQUIPO_JUGADOR> EQUIPO_JUGADOR { get; set; }
        public DbSet<ESTADIO> ESTADIO { get; set; }
        public DbSet<JUGADOR> JUGADOR { get; set; }
        public DbSet<PAIS> PAIS { get; set; }
        public DbSet<PARTIDO> PARTIDO { get; set; }
        public DbSet<RESULTADO> RESULTADO { get; set; }
    
        public virtual int SP_CIUDAD_DELETE(Nullable<decimal> pID_CIUDAD)
        {
            var pID_CIUDADParameter = pID_CIUDAD.HasValue ?
                new ObjectParameter("PID_CIUDAD", pID_CIUDAD) :
                new ObjectParameter("PID_CIUDAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CIUDAD_DELETE", pID_CIUDADParameter);
        }
    
        public virtual int SP_CIUDAD_INSERT(Nullable<decimal> pID_PAIS, string pNOMBRE)
        {
            var pID_PAISParameter = pID_PAIS.HasValue ?
                new ObjectParameter("PID_PAIS", pID_PAIS) :
                new ObjectParameter("PID_PAIS", typeof(decimal));
    
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CIUDAD_INSERT", pID_PAISParameter, pNOMBREParameter);
        }
    
        public virtual int SP_CIUDAD_UPDATE(Nullable<decimal> pID_PAIS, string pNOMBRE, Nullable<decimal> pID_CIUDAD)
        {
            var pID_PAISParameter = pID_PAIS.HasValue ?
                new ObjectParameter("PID_PAIS", pID_PAIS) :
                new ObjectParameter("PID_PAIS", typeof(decimal));
    
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            var pID_CIUDADParameter = pID_CIUDAD.HasValue ?
                new ObjectParameter("PID_CIUDAD", pID_CIUDAD) :
                new ObjectParameter("PID_CIUDAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CIUDAD_UPDATE", pID_PAISParameter, pNOMBREParameter, pID_CIUDADParameter);
        }
    
        public virtual int SP_COMPETENCIA_DELETE(Nullable<decimal> pID_COMPETENCIA)
        {
            var pID_COMPETENCIAParameter = pID_COMPETENCIA.HasValue ?
                new ObjectParameter("PID_COMPETENCIA", pID_COMPETENCIA) :
                new ObjectParameter("PID_COMPETENCIA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_COMPETENCIA_DELETE", pID_COMPETENCIAParameter);
        }
    
        public virtual int SP_COMPETENCIA_ESTADIO_DELETE(Nullable<decimal> pID_COMPETENCIA, Nullable<decimal> pID_ESTADIO)
        {
            var pID_COMPETENCIAParameter = pID_COMPETENCIA.HasValue ?
                new ObjectParameter("PID_COMPETENCIA", pID_COMPETENCIA) :
                new ObjectParameter("PID_COMPETENCIA", typeof(decimal));
    
            var pID_ESTADIOParameter = pID_ESTADIO.HasValue ?
                new ObjectParameter("PID_ESTADIO", pID_ESTADIO) :
                new ObjectParameter("PID_ESTADIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_COMPETENCIA_ESTADIO_DELETE", pID_COMPETENCIAParameter, pID_ESTADIOParameter);
        }
    
        public virtual int SP_COMPETENCIA_ESTADIO_INSERT(Nullable<decimal> pID_COMPETENCIA, Nullable<decimal> pID_ESTADIO)
        {
            var pID_COMPETENCIAParameter = pID_COMPETENCIA.HasValue ?
                new ObjectParameter("PID_COMPETENCIA", pID_COMPETENCIA) :
                new ObjectParameter("PID_COMPETENCIA", typeof(decimal));
    
            var pID_ESTADIOParameter = pID_ESTADIO.HasValue ?
                new ObjectParameter("PID_ESTADIO", pID_ESTADIO) :
                new ObjectParameter("PID_ESTADIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_COMPETENCIA_ESTADIO_INSERT", pID_COMPETENCIAParameter, pID_ESTADIOParameter);
        }
    
        public virtual int SP_COMPETENCIA_INSERT(string pNOMBRE, Nullable<System.DateTime> pFECHA_INICIO, Nullable<System.DateTime> pFECHA_FIN, Nullable<decimal> pESTADO_ACTUAL)
        {
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            var pFECHA_INICIOParameter = pFECHA_INICIO.HasValue ?
                new ObjectParameter("PFECHA_INICIO", pFECHA_INICIO) :
                new ObjectParameter("PFECHA_INICIO", typeof(System.DateTime));
    
            var pFECHA_FINParameter = pFECHA_FIN.HasValue ?
                new ObjectParameter("PFECHA_FIN", pFECHA_FIN) :
                new ObjectParameter("PFECHA_FIN", typeof(System.DateTime));
    
            var pESTADO_ACTUALParameter = pESTADO_ACTUAL.HasValue ?
                new ObjectParameter("PESTADO_ACTUAL", pESTADO_ACTUAL) :
                new ObjectParameter("PESTADO_ACTUAL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_COMPETENCIA_INSERT", pNOMBREParameter, pFECHA_INICIOParameter, pFECHA_FINParameter, pESTADO_ACTUALParameter);
        }
    
        public virtual int SP_COMPETENCIA_PAIS_DELETE(Nullable<decimal> pID_COMPETENCIA, Nullable<decimal> pID_PAIS)
        {
            var pID_COMPETENCIAParameter = pID_COMPETENCIA.HasValue ?
                new ObjectParameter("PID_COMPETENCIA", pID_COMPETENCIA) :
                new ObjectParameter("PID_COMPETENCIA", typeof(decimal));
    
            var pID_PAISParameter = pID_PAIS.HasValue ?
                new ObjectParameter("PID_PAIS", pID_PAIS) :
                new ObjectParameter("PID_PAIS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_COMPETENCIA_PAIS_DELETE", pID_COMPETENCIAParameter, pID_PAISParameter);
        }
    
        public virtual int SP_COMPETENCIA_PAIS_INSERT(Nullable<decimal> pID_COMPETENCIA, Nullable<decimal> pID_PAIS)
        {
            var pID_COMPETENCIAParameter = pID_COMPETENCIA.HasValue ?
                new ObjectParameter("PID_COMPETENCIA", pID_COMPETENCIA) :
                new ObjectParameter("PID_COMPETENCIA", typeof(decimal));
    
            var pID_PAISParameter = pID_PAIS.HasValue ?
                new ObjectParameter("PID_PAIS", pID_PAIS) :
                new ObjectParameter("PID_PAIS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_COMPETENCIA_PAIS_INSERT", pID_COMPETENCIAParameter, pID_PAISParameter);
        }
    
        public virtual int SP_COMPETENCIA_UPDATE(string pNOMBRE, Nullable<System.DateTime> pFECHA_INICIO, Nullable<System.DateTime> pFECHA_FIN, Nullable<decimal> pESTADO_ACTUAL, Nullable<decimal> pID_COMPETENCIA)
        {
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            var pFECHA_INICIOParameter = pFECHA_INICIO.HasValue ?
                new ObjectParameter("PFECHA_INICIO", pFECHA_INICIO) :
                new ObjectParameter("PFECHA_INICIO", typeof(System.DateTime));
    
            var pFECHA_FINParameter = pFECHA_FIN.HasValue ?
                new ObjectParameter("PFECHA_FIN", pFECHA_FIN) :
                new ObjectParameter("PFECHA_FIN", typeof(System.DateTime));
    
            var pESTADO_ACTUALParameter = pESTADO_ACTUAL.HasValue ?
                new ObjectParameter("PESTADO_ACTUAL", pESTADO_ACTUAL) :
                new ObjectParameter("PESTADO_ACTUAL", typeof(decimal));
    
            var pID_COMPETENCIAParameter = pID_COMPETENCIA.HasValue ?
                new ObjectParameter("PID_COMPETENCIA", pID_COMPETENCIA) :
                new ObjectParameter("PID_COMPETENCIA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_COMPETENCIA_UPDATE", pNOMBREParameter, pFECHA_INICIOParameter, pFECHA_FINParameter, pESTADO_ACTUALParameter, pID_COMPETENCIAParameter);
        }
    
        public virtual int SP_DESEMPENIO_DMD_DELETE(Nullable<decimal> pID_JUGADOR, Nullable<decimal> pID_RESULTADO)
        {
            var pID_JUGADORParameter = pID_JUGADOR.HasValue ?
                new ObjectParameter("PID_JUGADOR", pID_JUGADOR) :
                new ObjectParameter("PID_JUGADOR", typeof(decimal));
    
            var pID_RESULTADOParameter = pID_RESULTADO.HasValue ?
                new ObjectParameter("PID_RESULTADO", pID_RESULTADO) :
                new ObjectParameter("PID_RESULTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DESEMPENIO_DMD_DELETE", pID_JUGADORParameter, pID_RESULTADOParameter);
        }
    
        public virtual int SP_DESEMPENIO_DMD_INSERT(Nullable<decimal> pID_JUGADOR, Nullable<decimal> pID_RESULTADO, Nullable<decimal> pVELOCIDAD, Nullable<decimal> pCAPACIDAD_PASE, Nullable<decimal> pCAPACIDAD_MARCA, Nullable<decimal> pTIRO_GOL)
        {
            var pID_JUGADORParameter = pID_JUGADOR.HasValue ?
                new ObjectParameter("PID_JUGADOR", pID_JUGADOR) :
                new ObjectParameter("PID_JUGADOR", typeof(decimal));
    
            var pID_RESULTADOParameter = pID_RESULTADO.HasValue ?
                new ObjectParameter("PID_RESULTADO", pID_RESULTADO) :
                new ObjectParameter("PID_RESULTADO", typeof(decimal));
    
            var pVELOCIDADParameter = pVELOCIDAD.HasValue ?
                new ObjectParameter("PVELOCIDAD", pVELOCIDAD) :
                new ObjectParameter("PVELOCIDAD", typeof(decimal));
    
            var pCAPACIDAD_PASEParameter = pCAPACIDAD_PASE.HasValue ?
                new ObjectParameter("PCAPACIDAD_PASE", pCAPACIDAD_PASE) :
                new ObjectParameter("PCAPACIDAD_PASE", typeof(decimal));
    
            var pCAPACIDAD_MARCAParameter = pCAPACIDAD_MARCA.HasValue ?
                new ObjectParameter("PCAPACIDAD_MARCA", pCAPACIDAD_MARCA) :
                new ObjectParameter("PCAPACIDAD_MARCA", typeof(decimal));
    
            var pTIRO_GOLParameter = pTIRO_GOL.HasValue ?
                new ObjectParameter("PTIRO_GOL", pTIRO_GOL) :
                new ObjectParameter("PTIRO_GOL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DESEMPENIO_DMD_INSERT", pID_JUGADORParameter, pID_RESULTADOParameter, pVELOCIDADParameter, pCAPACIDAD_PASEParameter, pCAPACIDAD_MARCAParameter, pTIRO_GOLParameter);
        }
    
        public virtual int SP_DESEMPENIO_DMD_UPDATE(Nullable<decimal> pID_JUGADOR, Nullable<decimal> pID_RESULTADO, Nullable<decimal> pVELOCIDAD, Nullable<decimal> pCAPACIDAD_PASE, Nullable<decimal> pCAPACIDAD_MARCA, Nullable<decimal> pTIRO_GOL)
        {
            var pID_JUGADORParameter = pID_JUGADOR.HasValue ?
                new ObjectParameter("PID_JUGADOR", pID_JUGADOR) :
                new ObjectParameter("PID_JUGADOR", typeof(decimal));
    
            var pID_RESULTADOParameter = pID_RESULTADO.HasValue ?
                new ObjectParameter("PID_RESULTADO", pID_RESULTADO) :
                new ObjectParameter("PID_RESULTADO", typeof(decimal));
    
            var pVELOCIDADParameter = pVELOCIDAD.HasValue ?
                new ObjectParameter("PVELOCIDAD", pVELOCIDAD) :
                new ObjectParameter("PVELOCIDAD", typeof(decimal));
    
            var pCAPACIDAD_PASEParameter = pCAPACIDAD_PASE.HasValue ?
                new ObjectParameter("PCAPACIDAD_PASE", pCAPACIDAD_PASE) :
                new ObjectParameter("PCAPACIDAD_PASE", typeof(decimal));
    
            var pCAPACIDAD_MARCAParameter = pCAPACIDAD_MARCA.HasValue ?
                new ObjectParameter("PCAPACIDAD_MARCA", pCAPACIDAD_MARCA) :
                new ObjectParameter("PCAPACIDAD_MARCA", typeof(decimal));
    
            var pTIRO_GOLParameter = pTIRO_GOL.HasValue ?
                new ObjectParameter("PTIRO_GOL", pTIRO_GOL) :
                new ObjectParameter("PTIRO_GOL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DESEMPENIO_DMD_UPDATE", pID_JUGADORParameter, pID_RESULTADOParameter, pVELOCIDADParameter, pCAPACIDAD_PASEParameter, pCAPACIDAD_MARCAParameter, pTIRO_GOLParameter);
        }
    
        public virtual int SP_DESEMPENIO_PORTERO_DELETE(Nullable<decimal> pID_JUGADOR, Nullable<decimal> pID_RESULTADO)
        {
            var pID_JUGADORParameter = pID_JUGADOR.HasValue ?
                new ObjectParameter("PID_JUGADOR", pID_JUGADOR) :
                new ObjectParameter("PID_JUGADOR", typeof(decimal));
    
            var pID_RESULTADOParameter = pID_RESULTADO.HasValue ?
                new ObjectParameter("PID_RESULTADO", pID_RESULTADO) :
                new ObjectParameter("PID_RESULTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DESEMPENIO_PORTERO_DELETE", pID_JUGADORParameter, pID_RESULTADOParameter);
        }
    
        public virtual int SP_DESEMPENIO_PORTERO_INSERT(Nullable<decimal> pID_JUGADOR, Nullable<decimal> pID_RESULTADO, Nullable<decimal> pCAPACIDAD_ATAJAR, Nullable<decimal> pLUCHA1_1, Nullable<decimal> pANTICIPACION, Nullable<decimal> pREFLEJOS)
        {
            var pID_JUGADORParameter = pID_JUGADOR.HasValue ?
                new ObjectParameter("PID_JUGADOR", pID_JUGADOR) :
                new ObjectParameter("PID_JUGADOR", typeof(decimal));
    
            var pID_RESULTADOParameter = pID_RESULTADO.HasValue ?
                new ObjectParameter("PID_RESULTADO", pID_RESULTADO) :
                new ObjectParameter("PID_RESULTADO", typeof(decimal));
    
            var pCAPACIDAD_ATAJARParameter = pCAPACIDAD_ATAJAR.HasValue ?
                new ObjectParameter("PCAPACIDAD_ATAJAR", pCAPACIDAD_ATAJAR) :
                new ObjectParameter("PCAPACIDAD_ATAJAR", typeof(decimal));
    
            var pLUCHA1_1Parameter = pLUCHA1_1.HasValue ?
                new ObjectParameter("PLUCHA1_1", pLUCHA1_1) :
                new ObjectParameter("PLUCHA1_1", typeof(decimal));
    
            var pANTICIPACIONParameter = pANTICIPACION.HasValue ?
                new ObjectParameter("PANTICIPACION", pANTICIPACION) :
                new ObjectParameter("PANTICIPACION", typeof(decimal));
    
            var pREFLEJOSParameter = pREFLEJOS.HasValue ?
                new ObjectParameter("PREFLEJOS", pREFLEJOS) :
                new ObjectParameter("PREFLEJOS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DESEMPENIO_PORTERO_INSERT", pID_JUGADORParameter, pID_RESULTADOParameter, pCAPACIDAD_ATAJARParameter, pLUCHA1_1Parameter, pANTICIPACIONParameter, pREFLEJOSParameter);
        }
    
        public virtual int SP_DESEMPENIO_PORTERO_UPDATE(Nullable<decimal> pID_JUGADOR, Nullable<decimal> pID_RESULTADO, Nullable<decimal> pCAPACIDAD_ATAJAR, Nullable<decimal> pLUCHA1_1, Nullable<decimal> pANTICIPACION, Nullable<decimal> pREFLEJOS)
        {
            var pID_JUGADORParameter = pID_JUGADOR.HasValue ?
                new ObjectParameter("PID_JUGADOR", pID_JUGADOR) :
                new ObjectParameter("PID_JUGADOR", typeof(decimal));
    
            var pID_RESULTADOParameter = pID_RESULTADO.HasValue ?
                new ObjectParameter("PID_RESULTADO", pID_RESULTADO) :
                new ObjectParameter("PID_RESULTADO", typeof(decimal));
    
            var pCAPACIDAD_ATAJARParameter = pCAPACIDAD_ATAJAR.HasValue ?
                new ObjectParameter("PCAPACIDAD_ATAJAR", pCAPACIDAD_ATAJAR) :
                new ObjectParameter("PCAPACIDAD_ATAJAR", typeof(decimal));
    
            var pLUCHA1_1Parameter = pLUCHA1_1.HasValue ?
                new ObjectParameter("PLUCHA1_1", pLUCHA1_1) :
                new ObjectParameter("PLUCHA1_1", typeof(decimal));
    
            var pANTICIPACIONParameter = pANTICIPACION.HasValue ?
                new ObjectParameter("PANTICIPACION", pANTICIPACION) :
                new ObjectParameter("PANTICIPACION", typeof(decimal));
    
            var pREFLEJOSParameter = pREFLEJOS.HasValue ?
                new ObjectParameter("PREFLEJOS", pREFLEJOS) :
                new ObjectParameter("PREFLEJOS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DESEMPENIO_PORTERO_UPDATE", pID_JUGADORParameter, pID_RESULTADOParameter, pCAPACIDAD_ATAJARParameter, pLUCHA1_1Parameter, pANTICIPACIONParameter, pREFLEJOSParameter);
        }
    
        public virtual int SP_ENTRENADOR_DELETE(Nullable<decimal> pID_ENTRENADOR)
        {
            var pID_ENTRENADORParameter = pID_ENTRENADOR.HasValue ?
                new ObjectParameter("PID_ENTRENADOR", pID_ENTRENADOR) :
                new ObjectParameter("PID_ENTRENADOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ENTRENADOR_DELETE", pID_ENTRENADORParameter);
        }
    
        public virtual int SP_ENTRENADOR_INSERT(Nullable<decimal> pID_PAIS, string pNOMBRE, Nullable<decimal> pEDAD, Nullable<decimal> pCEDULA_IDENTIDAD, string pBIOGRAFIA, byte[] pFOTO)
        {
            var pID_PAISParameter = pID_PAIS.HasValue ?
                new ObjectParameter("PID_PAIS", pID_PAIS) :
                new ObjectParameter("PID_PAIS", typeof(decimal));
    
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            var pEDADParameter = pEDAD.HasValue ?
                new ObjectParameter("PEDAD", pEDAD) :
                new ObjectParameter("PEDAD", typeof(decimal));
    
            var pCEDULA_IDENTIDADParameter = pCEDULA_IDENTIDAD.HasValue ?
                new ObjectParameter("PCEDULA_IDENTIDAD", pCEDULA_IDENTIDAD) :
                new ObjectParameter("PCEDULA_IDENTIDAD", typeof(decimal));
    
            var pBIOGRAFIAParameter = pBIOGRAFIA != null ?
                new ObjectParameter("PBIOGRAFIA", pBIOGRAFIA) :
                new ObjectParameter("PBIOGRAFIA", typeof(string));
    
            var pFOTOParameter = pFOTO != null ?
                new ObjectParameter("PFOTO", pFOTO) :
                new ObjectParameter("PFOTO", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ENTRENADOR_INSERT", pID_PAISParameter, pNOMBREParameter, pEDADParameter, pCEDULA_IDENTIDADParameter, pBIOGRAFIAParameter, pFOTOParameter);
        }
    
        public virtual int SP_ENTRENADOR_UPDATE(Nullable<decimal> pID_PAIS, string pNOMBRE, Nullable<decimal> pEDAD, Nullable<decimal> pCEDULA_IDENTIDAD, string pBIOGRAFIA, byte[] pFOTO, Nullable<decimal> pID_ENTRENADOR)
        {
            var pID_PAISParameter = pID_PAIS.HasValue ?
                new ObjectParameter("PID_PAIS", pID_PAIS) :
                new ObjectParameter("PID_PAIS", typeof(decimal));
    
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            var pEDADParameter = pEDAD.HasValue ?
                new ObjectParameter("PEDAD", pEDAD) :
                new ObjectParameter("PEDAD", typeof(decimal));
    
            var pCEDULA_IDENTIDADParameter = pCEDULA_IDENTIDAD.HasValue ?
                new ObjectParameter("PCEDULA_IDENTIDAD", pCEDULA_IDENTIDAD) :
                new ObjectParameter("PCEDULA_IDENTIDAD", typeof(decimal));
    
            var pBIOGRAFIAParameter = pBIOGRAFIA != null ?
                new ObjectParameter("PBIOGRAFIA", pBIOGRAFIA) :
                new ObjectParameter("PBIOGRAFIA", typeof(string));
    
            var pFOTOParameter = pFOTO != null ?
                new ObjectParameter("PFOTO", pFOTO) :
                new ObjectParameter("PFOTO", typeof(byte[]));
    
            var pID_ENTRENADORParameter = pID_ENTRENADOR.HasValue ?
                new ObjectParameter("PID_ENTRENADOR", pID_ENTRENADOR) :
                new ObjectParameter("PID_ENTRENADOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ENTRENADOR_UPDATE", pID_PAISParameter, pNOMBREParameter, pEDADParameter, pCEDULA_IDENTIDADParameter, pBIOGRAFIAParameter, pFOTOParameter, pID_ENTRENADORParameter);
        }
    
        public virtual int SP_EQUIPO_COMPETENCIA_DELETE(Nullable<decimal> pID_EQUIPO, Nullable<decimal> pID_COMPETENCIA)
        {
            var pID_EQUIPOParameter = pID_EQUIPO.HasValue ?
                new ObjectParameter("PID_EQUIPO", pID_EQUIPO) :
                new ObjectParameter("PID_EQUIPO", typeof(decimal));
    
            var pID_COMPETENCIAParameter = pID_COMPETENCIA.HasValue ?
                new ObjectParameter("PID_COMPETENCIA", pID_COMPETENCIA) :
                new ObjectParameter("PID_COMPETENCIA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EQUIPO_COMPETENCIA_DELETE", pID_EQUIPOParameter, pID_COMPETENCIAParameter);
        }
    
        public virtual int SP_EQUIPO_COMPETENCIA_INSERT(Nullable<decimal> pID_EQUIPO, Nullable<decimal> pID_COMPETENCIA, Nullable<decimal> pPUNTOS, Nullable<decimal> pPOSICION)
        {
            var pID_EQUIPOParameter = pID_EQUIPO.HasValue ?
                new ObjectParameter("PID_EQUIPO", pID_EQUIPO) :
                new ObjectParameter("PID_EQUIPO", typeof(decimal));
    
            var pID_COMPETENCIAParameter = pID_COMPETENCIA.HasValue ?
                new ObjectParameter("PID_COMPETENCIA", pID_COMPETENCIA) :
                new ObjectParameter("PID_COMPETENCIA", typeof(decimal));
    
            var pPUNTOSParameter = pPUNTOS.HasValue ?
                new ObjectParameter("PPUNTOS", pPUNTOS) :
                new ObjectParameter("PPUNTOS", typeof(decimal));
    
            var pPOSICIONParameter = pPOSICION.HasValue ?
                new ObjectParameter("PPOSICION", pPOSICION) :
                new ObjectParameter("PPOSICION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EQUIPO_COMPETENCIA_INSERT", pID_EQUIPOParameter, pID_COMPETENCIAParameter, pPUNTOSParameter, pPOSICIONParameter);
        }
    
        public virtual int SP_EQUIPO_DELETE(Nullable<decimal> pID_EQUIPO)
        {
            var pID_EQUIPOParameter = pID_EQUIPO.HasValue ?
                new ObjectParameter("PID_EQUIPO", pID_EQUIPO) :
                new ObjectParameter("PID_EQUIPO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EQUIPO_DELETE", pID_EQUIPOParameter);
        }
    
        public virtual int SP_EQUIPO_INSERT(Nullable<decimal> pID_CIUDAD, Nullable<decimal> pID_ENTRENADOR, string pNOMBRE, Nullable<System.DateTime> pFECHA_FUNDACION, Nullable<decimal> pNUMERO_COPASGANADAS, byte[] pLOGOTIPO, string pTIPO)
        {
            var pID_CIUDADParameter = pID_CIUDAD.HasValue ?
                new ObjectParameter("PID_CIUDAD", pID_CIUDAD) :
                new ObjectParameter("PID_CIUDAD", typeof(decimal));
    
            var pID_ENTRENADORParameter = pID_ENTRENADOR.HasValue ?
                new ObjectParameter("PID_ENTRENADOR", pID_ENTRENADOR) :
                new ObjectParameter("PID_ENTRENADOR", typeof(decimal));
    
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            var pFECHA_FUNDACIONParameter = pFECHA_FUNDACION.HasValue ?
                new ObjectParameter("PFECHA_FUNDACION", pFECHA_FUNDACION) :
                new ObjectParameter("PFECHA_FUNDACION", typeof(System.DateTime));
    
            var pNUMERO_COPASGANADASParameter = pNUMERO_COPASGANADAS.HasValue ?
                new ObjectParameter("PNUMERO_COPASGANADAS", pNUMERO_COPASGANADAS) :
                new ObjectParameter("PNUMERO_COPASGANADAS", typeof(decimal));
    
            var pLOGOTIPOParameter = pLOGOTIPO != null ?
                new ObjectParameter("PLOGOTIPO", pLOGOTIPO) :
                new ObjectParameter("PLOGOTIPO", typeof(byte[]));
    
            var pTIPOParameter = pTIPO != null ?
                new ObjectParameter("PTIPO", pTIPO) :
                new ObjectParameter("PTIPO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EQUIPO_INSERT", pID_CIUDADParameter, pID_ENTRENADORParameter, pNOMBREParameter, pFECHA_FUNDACIONParameter, pNUMERO_COPASGANADASParameter, pLOGOTIPOParameter, pTIPOParameter);
        }
    
        public virtual int SP_EQUIPO_JUGADOR_DELETE(Nullable<decimal> pID_EQUIPO, Nullable<decimal> pID_JUGADOR)
        {
            var pID_EQUIPOParameter = pID_EQUIPO.HasValue ?
                new ObjectParameter("PID_EQUIPO", pID_EQUIPO) :
                new ObjectParameter("PID_EQUIPO", typeof(decimal));
    
            var pID_JUGADORParameter = pID_JUGADOR.HasValue ?
                new ObjectParameter("PID_JUGADOR", pID_JUGADOR) :
                new ObjectParameter("PID_JUGADOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EQUIPO_JUGADOR_DELETE", pID_EQUIPOParameter, pID_JUGADORParameter);
        }
    
        public virtual int SP_EQUIPO_JUGADOR_INSERT(Nullable<decimal> pID_EQUIPO, Nullable<decimal> pID_JUGADOR, Nullable<decimal> pNUMERO_CAMISOLA)
        {
            var pID_EQUIPOParameter = pID_EQUIPO.HasValue ?
                new ObjectParameter("PID_EQUIPO", pID_EQUIPO) :
                new ObjectParameter("PID_EQUIPO", typeof(decimal));
    
            var pID_JUGADORParameter = pID_JUGADOR.HasValue ?
                new ObjectParameter("PID_JUGADOR", pID_JUGADOR) :
                new ObjectParameter("PID_JUGADOR", typeof(decimal));
    
            var pNUMERO_CAMISOLAParameter = pNUMERO_CAMISOLA.HasValue ?
                new ObjectParameter("PNUMERO_CAMISOLA", pNUMERO_CAMISOLA) :
                new ObjectParameter("PNUMERO_CAMISOLA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EQUIPO_JUGADOR_INSERT", pID_EQUIPOParameter, pID_JUGADORParameter, pNUMERO_CAMISOLAParameter);
        }
    
        public virtual int SP_EQUIPO_UPDATE(Nullable<decimal> pID_CIUDAD, Nullable<decimal> pID_ENTRENADOR, string pNOMBRE, Nullable<System.DateTime> pFECHA_FUNDACION, Nullable<decimal> pNUMERO_COPASGANADAS, byte[] pLOGOTIPO, Nullable<decimal> pID_EQUIPO, string pTIPO)
        {
            var pID_CIUDADParameter = pID_CIUDAD.HasValue ?
                new ObjectParameter("PID_CIUDAD", pID_CIUDAD) :
                new ObjectParameter("PID_CIUDAD", typeof(decimal));
    
            var pID_ENTRENADORParameter = pID_ENTRENADOR.HasValue ?
                new ObjectParameter("PID_ENTRENADOR", pID_ENTRENADOR) :
                new ObjectParameter("PID_ENTRENADOR", typeof(decimal));
    
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            var pFECHA_FUNDACIONParameter = pFECHA_FUNDACION.HasValue ?
                new ObjectParameter("PFECHA_FUNDACION", pFECHA_FUNDACION) :
                new ObjectParameter("PFECHA_FUNDACION", typeof(System.DateTime));
    
            var pNUMERO_COPASGANADASParameter = pNUMERO_COPASGANADAS.HasValue ?
                new ObjectParameter("PNUMERO_COPASGANADAS", pNUMERO_COPASGANADAS) :
                new ObjectParameter("PNUMERO_COPASGANADAS", typeof(decimal));
    
            var pLOGOTIPOParameter = pLOGOTIPO != null ?
                new ObjectParameter("PLOGOTIPO", pLOGOTIPO) :
                new ObjectParameter("PLOGOTIPO", typeof(byte[]));
    
            var pID_EQUIPOParameter = pID_EQUIPO.HasValue ?
                new ObjectParameter("PID_EQUIPO", pID_EQUIPO) :
                new ObjectParameter("PID_EQUIPO", typeof(decimal));
    
            var pTIPOParameter = pTIPO != null ?
                new ObjectParameter("PTIPO", pTIPO) :
                new ObjectParameter("PTIPO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EQUIPO_UPDATE", pID_CIUDADParameter, pID_ENTRENADORParameter, pNOMBREParameter, pFECHA_FUNDACIONParameter, pNUMERO_COPASGANADASParameter, pLOGOTIPOParameter, pID_EQUIPOParameter, pTIPOParameter);
        }
    
        public virtual int SP_ESTADIO_DELETE(Nullable<decimal> pID_ESTADIO)
        {
            var pID_ESTADIOParameter = pID_ESTADIO.HasValue ?
                new ObjectParameter("PID_ESTADIO", pID_ESTADIO) :
                new ObjectParameter("PID_ESTADIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ESTADIO_DELETE", pID_ESTADIOParameter);
        }
    
        public virtual int SP_ESTADIO_INSERT(Nullable<decimal> pID_CIUDAD, string pNOMBRE, Nullable<decimal> pCAPACIDAD, Nullable<System.DateTime> pFECHA_INAUGURACION, string pHISTORIA)
        {
            var pID_CIUDADParameter = pID_CIUDAD.HasValue ?
                new ObjectParameter("PID_CIUDAD", pID_CIUDAD) :
                new ObjectParameter("PID_CIUDAD", typeof(decimal));
    
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            var pCAPACIDADParameter = pCAPACIDAD.HasValue ?
                new ObjectParameter("PCAPACIDAD", pCAPACIDAD) :
                new ObjectParameter("PCAPACIDAD", typeof(decimal));
    
            var pFECHA_INAUGURACIONParameter = pFECHA_INAUGURACION.HasValue ?
                new ObjectParameter("PFECHA_INAUGURACION", pFECHA_INAUGURACION) :
                new ObjectParameter("PFECHA_INAUGURACION", typeof(System.DateTime));
    
            var pHISTORIAParameter = pHISTORIA != null ?
                new ObjectParameter("PHISTORIA", pHISTORIA) :
                new ObjectParameter("PHISTORIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ESTADIO_INSERT", pID_CIUDADParameter, pNOMBREParameter, pCAPACIDADParameter, pFECHA_INAUGURACIONParameter, pHISTORIAParameter);
        }
    
        public virtual int SP_ESTADIO_UPDATE(Nullable<decimal> pID_CIUDAD, string pNOMBRE, Nullable<decimal> pCAPACIDAD, Nullable<System.DateTime> pFECHA_INAUGURACION, string pHISTORIA, Nullable<decimal> pID_ESTADIO)
        {
            var pID_CIUDADParameter = pID_CIUDAD.HasValue ?
                new ObjectParameter("PID_CIUDAD", pID_CIUDAD) :
                new ObjectParameter("PID_CIUDAD", typeof(decimal));
    
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            var pCAPACIDADParameter = pCAPACIDAD.HasValue ?
                new ObjectParameter("PCAPACIDAD", pCAPACIDAD) :
                new ObjectParameter("PCAPACIDAD", typeof(decimal));
    
            var pFECHA_INAUGURACIONParameter = pFECHA_INAUGURACION.HasValue ?
                new ObjectParameter("PFECHA_INAUGURACION", pFECHA_INAUGURACION) :
                new ObjectParameter("PFECHA_INAUGURACION", typeof(System.DateTime));
    
            var pHISTORIAParameter = pHISTORIA != null ?
                new ObjectParameter("PHISTORIA", pHISTORIA) :
                new ObjectParameter("PHISTORIA", typeof(string));
    
            var pID_ESTADIOParameter = pID_ESTADIO.HasValue ?
                new ObjectParameter("PID_ESTADIO", pID_ESTADIO) :
                new ObjectParameter("PID_ESTADIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ESTADIO_UPDATE", pID_CIUDADParameter, pNOMBREParameter, pCAPACIDADParameter, pFECHA_INAUGURACIONParameter, pHISTORIAParameter, pID_ESTADIOParameter);
        }
    
        public virtual int SP_JUGADOR_DELETE(Nullable<decimal> pID_JUGADOR)
        {
            var pID_JUGADORParameter = pID_JUGADOR.HasValue ?
                new ObjectParameter("PID_JUGADOR", pID_JUGADOR) :
                new ObjectParameter("PID_JUGADOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_JUGADOR_DELETE", pID_JUGADORParameter);
        }
    
        public virtual int SP_JUGADOR_INSERT(Nullable<decimal> pID_PAIS, string pNOMBRE, Nullable<decimal> pEDAD, Nullable<decimal> pPESO, string pPOSICION, Nullable<decimal> pCEDULA_IDENTIDAD, string pBIOGRAFIA, byte[] pFOTO)
        {
            var pID_PAISParameter = pID_PAIS.HasValue ?
                new ObjectParameter("PID_PAIS", pID_PAIS) :
                new ObjectParameter("PID_PAIS", typeof(decimal));
    
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            var pEDADParameter = pEDAD.HasValue ?
                new ObjectParameter("PEDAD", pEDAD) :
                new ObjectParameter("PEDAD", typeof(decimal));
    
            var pPESOParameter = pPESO.HasValue ?
                new ObjectParameter("PPESO", pPESO) :
                new ObjectParameter("PPESO", typeof(decimal));
    
            var pPOSICIONParameter = pPOSICION != null ?
                new ObjectParameter("PPOSICION", pPOSICION) :
                new ObjectParameter("PPOSICION", typeof(string));
    
            var pCEDULA_IDENTIDADParameter = pCEDULA_IDENTIDAD.HasValue ?
                new ObjectParameter("PCEDULA_IDENTIDAD", pCEDULA_IDENTIDAD) :
                new ObjectParameter("PCEDULA_IDENTIDAD", typeof(decimal));
    
            var pBIOGRAFIAParameter = pBIOGRAFIA != null ?
                new ObjectParameter("PBIOGRAFIA", pBIOGRAFIA) :
                new ObjectParameter("PBIOGRAFIA", typeof(string));
    
            var pFOTOParameter = pFOTO != null ?
                new ObjectParameter("PFOTO", pFOTO) :
                new ObjectParameter("PFOTO", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_JUGADOR_INSERT", pID_PAISParameter, pNOMBREParameter, pEDADParameter, pPESOParameter, pPOSICIONParameter, pCEDULA_IDENTIDADParameter, pBIOGRAFIAParameter, pFOTOParameter);
        }
    
        public virtual int SP_JUGADOR_UPDATE(Nullable<decimal> pID_PAIS, string pNOMBRE, Nullable<decimal> pEDAD, Nullable<decimal> pPESO, string pPOSICION, Nullable<decimal> pCEDULA_IDENTIDAD, string pBIOGRAFIA, byte[] pFOTO, Nullable<decimal> pID_JUGADOR)
        {
            var pID_PAISParameter = pID_PAIS.HasValue ?
                new ObjectParameter("PID_PAIS", pID_PAIS) :
                new ObjectParameter("PID_PAIS", typeof(decimal));
    
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            var pEDADParameter = pEDAD.HasValue ?
                new ObjectParameter("PEDAD", pEDAD) :
                new ObjectParameter("PEDAD", typeof(decimal));
    
            var pPESOParameter = pPESO.HasValue ?
                new ObjectParameter("PPESO", pPESO) :
                new ObjectParameter("PPESO", typeof(decimal));
    
            var pPOSICIONParameter = pPOSICION != null ?
                new ObjectParameter("PPOSICION", pPOSICION) :
                new ObjectParameter("PPOSICION", typeof(string));
    
            var pCEDULA_IDENTIDADParameter = pCEDULA_IDENTIDAD.HasValue ?
                new ObjectParameter("PCEDULA_IDENTIDAD", pCEDULA_IDENTIDAD) :
                new ObjectParameter("PCEDULA_IDENTIDAD", typeof(decimal));
    
            var pBIOGRAFIAParameter = pBIOGRAFIA != null ?
                new ObjectParameter("PBIOGRAFIA", pBIOGRAFIA) :
                new ObjectParameter("PBIOGRAFIA", typeof(string));
    
            var pFOTOParameter = pFOTO != null ?
                new ObjectParameter("PFOTO", pFOTO) :
                new ObjectParameter("PFOTO", typeof(byte[]));
    
            var pID_JUGADORParameter = pID_JUGADOR.HasValue ?
                new ObjectParameter("PID_JUGADOR", pID_JUGADOR) :
                new ObjectParameter("PID_JUGADOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_JUGADOR_UPDATE", pID_PAISParameter, pNOMBREParameter, pEDADParameter, pPESOParameter, pPOSICIONParameter, pCEDULA_IDENTIDADParameter, pBIOGRAFIAParameter, pFOTOParameter, pID_JUGADORParameter);
        }
    
        public virtual int SP_PAIS_DELETE(Nullable<decimal> pID_PAIS)
        {
            var pID_PAISParameter = pID_PAIS.HasValue ?
                new ObjectParameter("PID_PAIS", pID_PAIS) :
                new ObjectParameter("PID_PAIS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PAIS_DELETE", pID_PAISParameter);
        }
    
        public virtual int SP_PAIS_INSERT(string pNOMBRE, string pNACIONALIDAD)
        {
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            var pNACIONALIDADParameter = pNACIONALIDAD != null ?
                new ObjectParameter("PNACIONALIDAD", pNACIONALIDAD) :
                new ObjectParameter("PNACIONALIDAD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PAIS_INSERT", pNOMBREParameter, pNACIONALIDADParameter);
        }
    
        public virtual int SP_PAIS_UPDATE(Nullable<decimal> pID_PAIS, string pNOMBRE, string pNACIONALIDAD)
        {
            var pID_PAISParameter = pID_PAIS.HasValue ?
                new ObjectParameter("PID_PAIS", pID_PAIS) :
                new ObjectParameter("PID_PAIS", typeof(decimal));
    
            var pNOMBREParameter = pNOMBRE != null ?
                new ObjectParameter("PNOMBRE", pNOMBRE) :
                new ObjectParameter("PNOMBRE", typeof(string));
    
            var pNACIONALIDADParameter = pNACIONALIDAD != null ?
                new ObjectParameter("PNACIONALIDAD", pNACIONALIDAD) :
                new ObjectParameter("PNACIONALIDAD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PAIS_UPDATE", pID_PAISParameter, pNOMBREParameter, pNACIONALIDADParameter);
        }
    
        public virtual int SP_PARTIDO_DELETE(Nullable<decimal> pID_PARTIDO)
        {
            var pID_PARTIDOParameter = pID_PARTIDO.HasValue ?
                new ObjectParameter("PID_PARTIDO", pID_PARTIDO) :
                new ObjectParameter("PID_PARTIDO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PARTIDO_DELETE", pID_PARTIDOParameter);
        }
    
        public virtual int SP_PARTIDO_INSERT(Nullable<decimal> pID_COMPETENCIA, Nullable<decimal> pID_ESTADIO, Nullable<decimal> pID_EQUIPO_LOCAL, Nullable<decimal> pID_EQUIPO_VISITA, Nullable<System.DateTime> pFECHA_PARTIDO, Nullable<decimal> pHORA_INICIO, Nullable<decimal> pESTADO)
        {
            var pID_COMPETENCIAParameter = pID_COMPETENCIA.HasValue ?
                new ObjectParameter("PID_COMPETENCIA", pID_COMPETENCIA) :
                new ObjectParameter("PID_COMPETENCIA", typeof(decimal));
    
            var pID_ESTADIOParameter = pID_ESTADIO.HasValue ?
                new ObjectParameter("PID_ESTADIO", pID_ESTADIO) :
                new ObjectParameter("PID_ESTADIO", typeof(decimal));
    
            var pID_EQUIPO_LOCALParameter = pID_EQUIPO_LOCAL.HasValue ?
                new ObjectParameter("PID_EQUIPO_LOCAL", pID_EQUIPO_LOCAL) :
                new ObjectParameter("PID_EQUIPO_LOCAL", typeof(decimal));
    
            var pID_EQUIPO_VISITAParameter = pID_EQUIPO_VISITA.HasValue ?
                new ObjectParameter("PID_EQUIPO_VISITA", pID_EQUIPO_VISITA) :
                new ObjectParameter("PID_EQUIPO_VISITA", typeof(decimal));
    
            var pFECHA_PARTIDOParameter = pFECHA_PARTIDO.HasValue ?
                new ObjectParameter("PFECHA_PARTIDO", pFECHA_PARTIDO) :
                new ObjectParameter("PFECHA_PARTIDO", typeof(System.DateTime));
    
            var pHORA_INICIOParameter = pHORA_INICIO.HasValue ?
                new ObjectParameter("PHORA_INICIO", pHORA_INICIO) :
                new ObjectParameter("PHORA_INICIO", typeof(decimal));
    
            var pESTADOParameter = pESTADO.HasValue ?
                new ObjectParameter("PESTADO", pESTADO) :
                new ObjectParameter("PESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PARTIDO_INSERT", pID_COMPETENCIAParameter, pID_ESTADIOParameter, pID_EQUIPO_LOCALParameter, pID_EQUIPO_VISITAParameter, pFECHA_PARTIDOParameter, pHORA_INICIOParameter, pESTADOParameter);
        }
    
        public virtual int SP_PARTIDO_UPDATE(Nullable<decimal> pID_COMPETENCIA, Nullable<decimal> pID_ESTADIO, Nullable<decimal> pID_EQUIPO_LOCAL, Nullable<decimal> pID_EQUIPO_VISITA, Nullable<System.DateTime> pFECHA_PARTIDO, Nullable<decimal> pHORA_INICIO, Nullable<decimal> pESTADO, Nullable<decimal> pID_PARTIDO)
        {
            var pID_COMPETENCIAParameter = pID_COMPETENCIA.HasValue ?
                new ObjectParameter("PID_COMPETENCIA", pID_COMPETENCIA) :
                new ObjectParameter("PID_COMPETENCIA", typeof(decimal));
    
            var pID_ESTADIOParameter = pID_ESTADIO.HasValue ?
                new ObjectParameter("PID_ESTADIO", pID_ESTADIO) :
                new ObjectParameter("PID_ESTADIO", typeof(decimal));
    
            var pID_EQUIPO_LOCALParameter = pID_EQUIPO_LOCAL.HasValue ?
                new ObjectParameter("PID_EQUIPO_LOCAL", pID_EQUIPO_LOCAL) :
                new ObjectParameter("PID_EQUIPO_LOCAL", typeof(decimal));
    
            var pID_EQUIPO_VISITAParameter = pID_EQUIPO_VISITA.HasValue ?
                new ObjectParameter("PID_EQUIPO_VISITA", pID_EQUIPO_VISITA) :
                new ObjectParameter("PID_EQUIPO_VISITA", typeof(decimal));
    
            var pFECHA_PARTIDOParameter = pFECHA_PARTIDO.HasValue ?
                new ObjectParameter("PFECHA_PARTIDO", pFECHA_PARTIDO) :
                new ObjectParameter("PFECHA_PARTIDO", typeof(System.DateTime));
    
            var pHORA_INICIOParameter = pHORA_INICIO.HasValue ?
                new ObjectParameter("PHORA_INICIO", pHORA_INICIO) :
                new ObjectParameter("PHORA_INICIO", typeof(decimal));
    
            var pESTADOParameter = pESTADO.HasValue ?
                new ObjectParameter("PESTADO", pESTADO) :
                new ObjectParameter("PESTADO", typeof(decimal));
    
            var pID_PARTIDOParameter = pID_PARTIDO.HasValue ?
                new ObjectParameter("PID_PARTIDO", pID_PARTIDO) :
                new ObjectParameter("PID_PARTIDO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PARTIDO_UPDATE", pID_COMPETENCIAParameter, pID_ESTADIOParameter, pID_EQUIPO_LOCALParameter, pID_EQUIPO_VISITAParameter, pFECHA_PARTIDOParameter, pHORA_INICIOParameter, pESTADOParameter, pID_PARTIDOParameter);
        }
    
        public virtual int SP_RESULTADO_DELETE(Nullable<decimal> pID_RESULTADO)
        {
            var pID_RESULTADOParameter = pID_RESULTADO.HasValue ?
                new ObjectParameter("PID_RESULTADO", pID_RESULTADO) :
                new ObjectParameter("PID_RESULTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RESULTADO_DELETE", pID_RESULTADOParameter);
        }
    
        public virtual int SP_RESULTADO_INSERT(Nullable<decimal> pID_PARTIDO, Nullable<decimal> pPRIMERT_GOLES_EQUIPO1, Nullable<decimal> pPRIMERT_GOLES_EQUIPO2, Nullable<decimal> pSEGUNDOT_GOLES_EQUIPO1, Nullable<decimal> pSEGUNDOT_GOLES_EQUIPO2, Nullable<decimal> pTIEMPOEXTRA_GOLES_EQUIPO1, Nullable<decimal> pTIEMPOEXTRA_GOLES_EQUIPO2, Nullable<decimal> pPENALES_GOLES_EQUIPO1, Nullable<decimal> pPENALES_GOLES_EQUIPO2, Nullable<decimal> pTARJETAS_A_EQUIPO1, Nullable<decimal> pTARJETAS_A_EQUIPO2, Nullable<decimal> pTARJETAS_R_EQUIPO1, Nullable<decimal> pTARJETAS_R_EQUIPO2)
        {
            var pID_PARTIDOParameter = pID_PARTIDO.HasValue ?
                new ObjectParameter("PID_PARTIDO", pID_PARTIDO) :
                new ObjectParameter("PID_PARTIDO", typeof(decimal));
    
            var pPRIMERT_GOLES_EQUIPO1Parameter = pPRIMERT_GOLES_EQUIPO1.HasValue ?
                new ObjectParameter("PPRIMERT_GOLES_EQUIPO1", pPRIMERT_GOLES_EQUIPO1) :
                new ObjectParameter("PPRIMERT_GOLES_EQUIPO1", typeof(decimal));
    
            var pPRIMERT_GOLES_EQUIPO2Parameter = pPRIMERT_GOLES_EQUIPO2.HasValue ?
                new ObjectParameter("PPRIMERT_GOLES_EQUIPO2", pPRIMERT_GOLES_EQUIPO2) :
                new ObjectParameter("PPRIMERT_GOLES_EQUIPO2", typeof(decimal));
    
            var pSEGUNDOT_GOLES_EQUIPO1Parameter = pSEGUNDOT_GOLES_EQUIPO1.HasValue ?
                new ObjectParameter("PSEGUNDOT_GOLES_EQUIPO1", pSEGUNDOT_GOLES_EQUIPO1) :
                new ObjectParameter("PSEGUNDOT_GOLES_EQUIPO1", typeof(decimal));
    
            var pSEGUNDOT_GOLES_EQUIPO2Parameter = pSEGUNDOT_GOLES_EQUIPO2.HasValue ?
                new ObjectParameter("PSEGUNDOT_GOLES_EQUIPO2", pSEGUNDOT_GOLES_EQUIPO2) :
                new ObjectParameter("PSEGUNDOT_GOLES_EQUIPO2", typeof(decimal));
    
            var pTIEMPOEXTRA_GOLES_EQUIPO1Parameter = pTIEMPOEXTRA_GOLES_EQUIPO1.HasValue ?
                new ObjectParameter("PTIEMPOEXTRA_GOLES_EQUIPO1", pTIEMPOEXTRA_GOLES_EQUIPO1) :
                new ObjectParameter("PTIEMPOEXTRA_GOLES_EQUIPO1", typeof(decimal));
    
            var pTIEMPOEXTRA_GOLES_EQUIPO2Parameter = pTIEMPOEXTRA_GOLES_EQUIPO2.HasValue ?
                new ObjectParameter("PTIEMPOEXTRA_GOLES_EQUIPO2", pTIEMPOEXTRA_GOLES_EQUIPO2) :
                new ObjectParameter("PTIEMPOEXTRA_GOLES_EQUIPO2", typeof(decimal));
    
            var pPENALES_GOLES_EQUIPO1Parameter = pPENALES_GOLES_EQUIPO1.HasValue ?
                new ObjectParameter("PPENALES_GOLES_EQUIPO1", pPENALES_GOLES_EQUIPO1) :
                new ObjectParameter("PPENALES_GOLES_EQUIPO1", typeof(decimal));
    
            var pPENALES_GOLES_EQUIPO2Parameter = pPENALES_GOLES_EQUIPO2.HasValue ?
                new ObjectParameter("PPENALES_GOLES_EQUIPO2", pPENALES_GOLES_EQUIPO2) :
                new ObjectParameter("PPENALES_GOLES_EQUIPO2", typeof(decimal));
    
            var pTARJETAS_A_EQUIPO1Parameter = pTARJETAS_A_EQUIPO1.HasValue ?
                new ObjectParameter("PTARJETAS_A_EQUIPO1", pTARJETAS_A_EQUIPO1) :
                new ObjectParameter("PTARJETAS_A_EQUIPO1", typeof(decimal));
    
            var pTARJETAS_A_EQUIPO2Parameter = pTARJETAS_A_EQUIPO2.HasValue ?
                new ObjectParameter("PTARJETAS_A_EQUIPO2", pTARJETAS_A_EQUIPO2) :
                new ObjectParameter("PTARJETAS_A_EQUIPO2", typeof(decimal));
    
            var pTARJETAS_R_EQUIPO1Parameter = pTARJETAS_R_EQUIPO1.HasValue ?
                new ObjectParameter("PTARJETAS_R_EQUIPO1", pTARJETAS_R_EQUIPO1) :
                new ObjectParameter("PTARJETAS_R_EQUIPO1", typeof(decimal));
    
            var pTARJETAS_R_EQUIPO2Parameter = pTARJETAS_R_EQUIPO2.HasValue ?
                new ObjectParameter("PTARJETAS_R_EQUIPO2", pTARJETAS_R_EQUIPO2) :
                new ObjectParameter("PTARJETAS_R_EQUIPO2", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RESULTADO_INSERT", pID_PARTIDOParameter, pPRIMERT_GOLES_EQUIPO1Parameter, pPRIMERT_GOLES_EQUIPO2Parameter, pSEGUNDOT_GOLES_EQUIPO1Parameter, pSEGUNDOT_GOLES_EQUIPO2Parameter, pTIEMPOEXTRA_GOLES_EQUIPO1Parameter, pTIEMPOEXTRA_GOLES_EQUIPO2Parameter, pPENALES_GOLES_EQUIPO1Parameter, pPENALES_GOLES_EQUIPO2Parameter, pTARJETAS_A_EQUIPO1Parameter, pTARJETAS_A_EQUIPO2Parameter, pTARJETAS_R_EQUIPO1Parameter, pTARJETAS_R_EQUIPO2Parameter);
        }
    
        public virtual int SP_RESULTADO_UPDATE(Nullable<decimal> pID_PARTIDO, Nullable<decimal> pPRIMERT_GOLES_EQUIPO1, Nullable<decimal> pPRIMERT_GOLES_EQUIPO2, Nullable<decimal> pSEGUNDOT_GOLES_EQUIPO1, Nullable<decimal> pSEGUNDOT_GOLES_EQUIPO2, Nullable<decimal> pTIEMPOEXTRA_GOLES_EQUIPO1, Nullable<decimal> pTIEMPOEXTRA_GOLES_EQUIPO2, Nullable<decimal> pPENALES_GOLES_EQUIPO1, Nullable<decimal> pPENALES_GOLES_EQUIPO2, Nullable<decimal> pTARJETAS_A_EQUIPO1, Nullable<decimal> pTARJETAS_A_EQUIPO2, Nullable<decimal> pTARJETAS_R_EQUIPO1, Nullable<decimal> pTARJETAS_R_EQUIPO2, Nullable<decimal> pID_RESULTADO)
        {
            var pID_PARTIDOParameter = pID_PARTIDO.HasValue ?
                new ObjectParameter("PID_PARTIDO", pID_PARTIDO) :
                new ObjectParameter("PID_PARTIDO", typeof(decimal));
    
            var pPRIMERT_GOLES_EQUIPO1Parameter = pPRIMERT_GOLES_EQUIPO1.HasValue ?
                new ObjectParameter("PPRIMERT_GOLES_EQUIPO1", pPRIMERT_GOLES_EQUIPO1) :
                new ObjectParameter("PPRIMERT_GOLES_EQUIPO1", typeof(decimal));
    
            var pPRIMERT_GOLES_EQUIPO2Parameter = pPRIMERT_GOLES_EQUIPO2.HasValue ?
                new ObjectParameter("PPRIMERT_GOLES_EQUIPO2", pPRIMERT_GOLES_EQUIPO2) :
                new ObjectParameter("PPRIMERT_GOLES_EQUIPO2", typeof(decimal));
    
            var pSEGUNDOT_GOLES_EQUIPO1Parameter = pSEGUNDOT_GOLES_EQUIPO1.HasValue ?
                new ObjectParameter("PSEGUNDOT_GOLES_EQUIPO1", pSEGUNDOT_GOLES_EQUIPO1) :
                new ObjectParameter("PSEGUNDOT_GOLES_EQUIPO1", typeof(decimal));
    
            var pSEGUNDOT_GOLES_EQUIPO2Parameter = pSEGUNDOT_GOLES_EQUIPO2.HasValue ?
                new ObjectParameter("PSEGUNDOT_GOLES_EQUIPO2", pSEGUNDOT_GOLES_EQUIPO2) :
                new ObjectParameter("PSEGUNDOT_GOLES_EQUIPO2", typeof(decimal));
    
            var pTIEMPOEXTRA_GOLES_EQUIPO1Parameter = pTIEMPOEXTRA_GOLES_EQUIPO1.HasValue ?
                new ObjectParameter("PTIEMPOEXTRA_GOLES_EQUIPO1", pTIEMPOEXTRA_GOLES_EQUIPO1) :
                new ObjectParameter("PTIEMPOEXTRA_GOLES_EQUIPO1", typeof(decimal));
    
            var pTIEMPOEXTRA_GOLES_EQUIPO2Parameter = pTIEMPOEXTRA_GOLES_EQUIPO2.HasValue ?
                new ObjectParameter("PTIEMPOEXTRA_GOLES_EQUIPO2", pTIEMPOEXTRA_GOLES_EQUIPO2) :
                new ObjectParameter("PTIEMPOEXTRA_GOLES_EQUIPO2", typeof(decimal));
    
            var pPENALES_GOLES_EQUIPO1Parameter = pPENALES_GOLES_EQUIPO1.HasValue ?
                new ObjectParameter("PPENALES_GOLES_EQUIPO1", pPENALES_GOLES_EQUIPO1) :
                new ObjectParameter("PPENALES_GOLES_EQUIPO1", typeof(decimal));
    
            var pPENALES_GOLES_EQUIPO2Parameter = pPENALES_GOLES_EQUIPO2.HasValue ?
                new ObjectParameter("PPENALES_GOLES_EQUIPO2", pPENALES_GOLES_EQUIPO2) :
                new ObjectParameter("PPENALES_GOLES_EQUIPO2", typeof(decimal));
    
            var pTARJETAS_A_EQUIPO1Parameter = pTARJETAS_A_EQUIPO1.HasValue ?
                new ObjectParameter("PTARJETAS_A_EQUIPO1", pTARJETAS_A_EQUIPO1) :
                new ObjectParameter("PTARJETAS_A_EQUIPO1", typeof(decimal));
    
            var pTARJETAS_A_EQUIPO2Parameter = pTARJETAS_A_EQUIPO2.HasValue ?
                new ObjectParameter("PTARJETAS_A_EQUIPO2", pTARJETAS_A_EQUIPO2) :
                new ObjectParameter("PTARJETAS_A_EQUIPO2", typeof(decimal));
    
            var pTARJETAS_R_EQUIPO1Parameter = pTARJETAS_R_EQUIPO1.HasValue ?
                new ObjectParameter("PTARJETAS_R_EQUIPO1", pTARJETAS_R_EQUIPO1) :
                new ObjectParameter("PTARJETAS_R_EQUIPO1", typeof(decimal));
    
            var pTARJETAS_R_EQUIPO2Parameter = pTARJETAS_R_EQUIPO2.HasValue ?
                new ObjectParameter("PTARJETAS_R_EQUIPO2", pTARJETAS_R_EQUIPO2) :
                new ObjectParameter("PTARJETAS_R_EQUIPO2", typeof(decimal));
    
            var pID_RESULTADOParameter = pID_RESULTADO.HasValue ?
                new ObjectParameter("PID_RESULTADO", pID_RESULTADO) :
                new ObjectParameter("PID_RESULTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RESULTADO_UPDATE", pID_PARTIDOParameter, pPRIMERT_GOLES_EQUIPO1Parameter, pPRIMERT_GOLES_EQUIPO2Parameter, pSEGUNDOT_GOLES_EQUIPO1Parameter, pSEGUNDOT_GOLES_EQUIPO2Parameter, pTIEMPOEXTRA_GOLES_EQUIPO1Parameter, pTIEMPOEXTRA_GOLES_EQUIPO2Parameter, pPENALES_GOLES_EQUIPO1Parameter, pPENALES_GOLES_EQUIPO2Parameter, pTARJETAS_A_EQUIPO1Parameter, pTARJETAS_A_EQUIPO2Parameter, pTARJETAS_R_EQUIPO1Parameter, pTARJETAS_R_EQUIPO2Parameter, pID_RESULTADOParameter);
        }
    }
}
