//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO
    {
        public EQUIPO()
        {
            this.EQUIPO_COMPETENCIA = new HashSet<EQUIPO_COMPETENCIA>();
            this.EQUIPO_JUGADOR = new HashSet<EQUIPO_JUGADOR>();
            this.PARTIDO = new HashSet<PARTIDO>();
            this.PARTIDO1 = new HashSet<PARTIDO>();
        }
    
        public int ID_EQUIPO { get; set; }
        public int ID_CIUDAD { get; set; }
        public int ID_ENTRENADOR { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> FECHA_FUNDACION { get; set; }
        public Nullable<int> NUMERO_COPASGANADAS { get; set; }
        public byte[] LOGOTIPO { get; set; }
        public string TIPO { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ENTRENADOR ENTRENADOR { get; set; }
        public virtual ICollection<EQUIPO_COMPETENCIA> EQUIPO_COMPETENCIA { get; set; }
        public virtual ICollection<EQUIPO_JUGADOR> EQUIPO_JUGADOR { get; set; }
        public virtual ICollection<PARTIDO> PARTIDO { get; set; }
        public virtual ICollection<PARTIDO> PARTIDO1 { get; set; }
    }
}
