//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADIO
    {
        public ESTADIO()
        {
            this.PARTIDO = new HashSet<PARTIDO>();
            this.COMPETENCIA = new HashSet<COMPETENCIA>();
        }
    
        public int ID_ESTADIO { get; set; }
        public int ID_CIUDAD { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> CAPACIDAD { get; set; }
        public Nullable<System.DateTime> FECHA_INAUGURACION { get; set; }
        public string HISTORIA { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ICollection<PARTIDO> PARTIDO { get; set; }
        public virtual ICollection<COMPETENCIA> COMPETENCIA { get; set; }
    }
}
