//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUGADOR
    {
        public JUGADOR()
        {
            this.DESEMPENIO_DMD = new HashSet<DESEMPENIO_DMD>();
            this.DESEMPENIO_PORTERO = new HashSet<DESEMPENIO_PORTERO>();
            this.EQUIPO_JUGADOR = new HashSet<EQUIPO_JUGADOR>();
        }
    
        public decimal ID_JUGADOR { get; set; }
        public decimal ID_PAIS { get; set; }
        public Nullable<decimal> CEDULA_IDENTIDAD { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> EDAD { get; set; }
        public Nullable<decimal> PESO { get; set; }
        public string POSICION { get; set; }
        public string BIOGRAFIA { get; set; }
        public byte[] FOTO { get; set; }
    
        public virtual ICollection<DESEMPENIO_DMD> DESEMPENIO_DMD { get; set; }
        public virtual ICollection<DESEMPENIO_PORTERO> DESEMPENIO_PORTERO { get; set; }
        public virtual ICollection<EQUIPO_JUGADOR> EQUIPO_JUGADOR { get; set; }
        public virtual PAIS PAIS { get; set; }
    }
}
