//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIS
    {
        public PAIS()
        {
            this.CIUDAD = new HashSet<CIUDAD>();
            this.ENTRENADOR = new HashSet<ENTRENADOR>();
            this.JUGADOR = new HashSet<JUGADOR>();
            this.COMPETENCIA = new HashSet<COMPETENCIA>();
        }
    
        public int ID_PAIS { get; set; }
        public string NOMBRE { get; set; }
        public string NACIONALIDAD { get; set; }
    
        public virtual ICollection<CIUDAD> CIUDAD { get; set; }
        public virtual ICollection<ENTRENADOR> ENTRENADOR { get; set; }
        public virtual ICollection<JUGADOR> JUGADOR { get; set; }
        public virtual ICollection<COMPETENCIA> COMPETENCIA { get; set; }
    }
}
