//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIDO
    {
        public PARTIDO()
        {
            this.RESULTADO = new HashSet<RESULTADO>();
        }
    
        public decimal ID_PARTIDO { get; set; }
        public decimal ID_COMPETENCIA { get; set; }
        public decimal ID_ESTADIO { get; set; }
        public decimal ID_EQUIPO_LOCAL { get; set; }
        public decimal ID_EQUIPO_VISITA { get; set; }
        public Nullable<System.DateTime> FECHA_PARTIDO { get; set; }
        public Nullable<decimal> HORA_INICIO { get; set; }
        public Nullable<decimal> ESTADO { get; set; }
    
        public virtual COMPETENCIA COMPETENCIA { get; set; }
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual EQUIPO EQUIPO1 { get; set; }
        public virtual ESTADIO ESTADIO { get; set; }
        public virtual ICollection<RESULTADO> RESULTADO { get; set; }
    }
}
