//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESULTADO
    {
        public RESULTADO()
        {
            this.DESEMPENIO_DMD = new HashSet<DESEMPENIO_DMD>();
            this.DESEMPENIO_PORTERO = new HashSet<DESEMPENIO_PORTERO>();
        }
    
        public decimal ID_RESULTADO { get; set; }
        public decimal ID_PARTIDO { get; set; }
        public Nullable<decimal> PRIMERT_GOLES_EQUIPO1 { get; set; }
        public Nullable<decimal> PRIMERT_GOLES_EQUIPO2 { get; set; }
        public Nullable<decimal> SEGUNDOT_GOLES_EQUIPO1 { get; set; }
        public Nullable<decimal> SEGUNDOT_GOLES_EQUIPO2 { get; set; }
        public Nullable<decimal> TIEMPOEXTRA_GOLES_EQUIPO1 { get; set; }
        public Nullable<decimal> TIEMPOEXTRA_GOLES_EQUIPO2 { get; set; }
        public Nullable<decimal> PENALES_GOLES_EQUIPO1 { get; set; }
        public Nullable<decimal> PENALES_GOLES_EQUIPO2 { get; set; }
        public Nullable<decimal> TARJETAS_A_EQUIPO1 { get; set; }
        public Nullable<decimal> TARJETAS_A_EQUIPO2 { get; set; }
        public Nullable<decimal> TARJETAS_R_EQUIPO1 { get; set; }
        public Nullable<decimal> TARJETAS_R_EQUIPO2 { get; set; }
    
        public virtual ICollection<DESEMPENIO_DMD> DESEMPENIO_DMD { get; set; }
        public virtual ICollection<DESEMPENIO_PORTERO> DESEMPENIO_PORTERO { get; set; }
        public virtual PARTIDO PARTIDO { get; set; }
    }
}
