//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DESEMPENIO_PORTERO
    {
        public decimal ID_JUGADOR { get; set; }
        public decimal ID_RESULTADO { get; set; }
        public Nullable<decimal> CAPACIDAD_ATAJAR { get; set; }
        public Nullable<decimal> LUCHA1_1 { get; set; }
        public Nullable<decimal> ANTICIPACION { get; set; }
        public Nullable<decimal> REFLEJOS { get; set; }
    }
}
