//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DESEMPENIO_DMD
    {
        public decimal ID_JUGADOR { get; set; }
        public decimal ID_RESULTADO { get; set; }
        public Nullable<decimal> VELOCIDAD { get; set; }
        public Nullable<decimal> CAPACIDAD_PASE { get; set; }
        public Nullable<decimal> CAPACIDAD_MARCA { get; set; }
        public Nullable<decimal> TIRO_GOL { get; set; }
    }
}
