//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EQUIPO
    {
        public decimal ID_EQUIPO { get; set; }
        public decimal ID_CIUDAD { get; set; }
        public decimal ID_ENTRENADOR { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> FECHA_FUNDACION { get; set; }
        public Nullable<decimal> NUMERO_COPASGANADAS { get; set; }
        public byte[] LOGOTIPO { get; set; }
        public string TIPO { get; set; }
    }
}
