//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EQUIPO_COMPETENCIA
    {
        public decimal ID_EQUIPO { get; set; }
        public decimal ID_COMPETENCIA { get; set; }
        public Nullable<decimal> PUNTOS { get; set; }
        public Nullable<decimal> POSICION { get; set; }
    }
}
