//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PAIS
    {
        public decimal ID_PAIS { get; set; }
        public string NOMBRE { get; set; }
        public string NACIONALIDAD { get; set; }
    }
}
